#!/usr/bin/ksh
Tmp="/tmp/$$"
TmpDir="/tmp/dir$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15

gawk '
function ltrim(s) {sub(/^ */, "", s); return s}
function rtrim(s) {sub(/ *$/, "", s); return s}
function trim(s) {return rtrim(ltrim(s));}

/^[ ]*((public)|(private))/ {
     sz = $0;
     sub(/[)].*$/, ")", sz);
     print trim(sz)
}' $1 | sort
